// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalonManagementService.Api.Models;

#nullable disable

namespace SalonManagementService.Api.Migrations
{
    [DbContext(typeof(SalonDbContext))]
    [Migration("20260212225131_AddIsActiveToStylist")]
    partial class AddIsActiveToStylist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalonManagementService.Api.Models.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("StylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.AppointmentStylistService", b =>
                {
                    b.Property<Guid>("AppointmentStylistServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StylistServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppointmentStylistServiceId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("StylistServiceId");

                    b.ToTable("AppointmentStylistServices");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.Stylist", b =>
                {
                    b.Property<Guid>("StylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChairName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WorkEndTime24H")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WorkStartTime24H")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StylistId");

                    b.ToTable("Stylists");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.StylistService", b =>
                {
                    b.Property<Guid>("StylistServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StylistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StylistServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StylistId");

                    b.ToTable("StylistServices");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.Appointment", b =>
                {
                    b.HasOne("SalonManagementService.Api.Models.Stylist", "Stylist")
                        .WithMany("Appointments")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.AppointmentStylistService", b =>
                {
                    b.HasOne("SalonManagementService.Api.Models.Appointment", "Appointment")
                        .WithMany("AppointmentStylistServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalonManagementService.Api.Models.StylistService", "StylistService")
                        .WithMany("AppointmentStylistServices")
                        .HasForeignKey("StylistServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("StylistService");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.StylistService", b =>
                {
                    b.HasOne("SalonManagementService.Api.Models.Service", "Service")
                        .WithMany("StylistServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalonManagementService.Api.Models.Stylist", "Stylist")
                        .WithMany("StylistServices")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentStylistServices");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.Service", b =>
                {
                    b.Navigation("StylistServices");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.Stylist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("StylistServices");
                });

            modelBuilder.Entity("SalonManagementService.Api.Models.StylistService", b =>
                {
                    b.Navigation("AppointmentStylistServices");
                });
#pragma warning restore 612, 618
        }
    }
}
