name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Assignment2
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    env:
      SWA_RUNTIME_NODE_VERSION: "20"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: wordle-app
        run: npm install

      - name: Generate static site
        working-directory: wordle-app
        run: npm run generate

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_MEADOW_06F41AE1E }}
          action: upload
          skip_app_build: true
          app_location: wordle-app
          output_location: .output/public
